version: '3.1'

services:
  mongo:
    container_name: authz-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: authz
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
  authz:
    container_name: authz-auth
    build:
      context: ./
      dockerfile: ./authz/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
  dbpi:
    container_name: authz-dbapi
    build:
      context: ./
      dockerfile: ./db_api/Dockerfile
    expose:
      - "80"
    restart: unless-stopped