# Vouch Proxy configuration
# bare minimum to get Vouch Proxy running with github

vouch:
  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  # for github that's only one domain since they only allow one callback URL
  # https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls
  # each of these domains must serve the url https://login.$domains[0] https://login.$domains[1] ...
  loglevel: debug
  testing: true
  domains:
  - localhost
  - host.docker.internal
  - http://authz-vouch:9090/auth
  - alaska.edu
  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate
  allowAllUsers: false

  cookie:
    # allow the jwt/cookie to be set into http://yourdomain.com (defaults to true, requiring https://yourdomain.com) 
    secure: false
    # vouch.cookie.domain must be set when enabling allowAllUsers
    #  domain: yourdomain.com


oauth:
  # Generic OpenID Connect
  # including okta
  provider: oidc
  client_id: 123456789
  client_secret: 123456
  auth_url: http://localhost:8060/authorize
  token_url: http://host.docker.internal:8060/token
  user_info_url: http://host.docker.internal:8060/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: http://localhost/auth